import { createHash } from 'node:crypto'
import { bytes, figure, grouped, setting } from './format.js'
import type { CatalogueScenario, EngineKey, LatencyResult, Results, RunFacts, ScenarioResult, SizeFacts } from './results.js'
import { ENGINE_KEYS, ENGINE_NAMES } from './results.js'

/*
 * `docs/performance.md`'s generated region, from `results.json` and nothing
 * else (0034). `scripts/performance-doc.test.mjs` fails when the committed
 * region is not what this renders.
 *
 * Deterministic on any machine: times are the ISO strings the run recorded,
 * printed as they are, never a Date; numbers go through `format.ts`, never
 * the locale. Node built-ins only, so that test renders without a build.
 */

/*
 * The region's markers, in the repository's one grammar for generated Markdown
 * (scripts/generated-block.mjs, 0035): this program writes it, from the
 * measurement. Before the first measurement there is no source, so the page's
 * region names none, and the first render replaces that marker with this one.
 */
export const START_MARKER = '<!-- generated by packages/data-performance/src/render-cli.ts from docs/performance/results.json; do not edit -->'
export const UNMEASURED_MARKER = '<!-- generated by packages/data-performance/src/render-cli.ts; do not edit -->'
export const END_MARKER = '<!-- end generated -->'

/** A figure, or the words for a percentile resting on fewer than ten samples. */
const cell = (value: number | null): string => (value === null ? 'n too small' : figure(value))

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const line = (cells: readonly string[]): string => `| ${cells.join(' | ')} |`
  return [line(headers), line(headers.map(() => '---')), ...rows.map(line)].join('\n')
}

/** A short digest of what was measured, for the reader to compare with `node scripts/performance-stale.mjs --describe`. */
export function productDigest(product: Results['product']): string {
  const sorted = (record: Record<string, string>): Array<[string, string]> => Object.entries(record).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
  const text = JSON.stringify({ files: sorted(product.files), packages: sorted(product.packages), build: sorted(product.build) })
  return createHash('sha256').update(text).digest('hex').slice(0, 12)
}

/** The drivers and the server's own libraries, named with their versions; the rest of the closure is counted. */
const NAMED_LIBRARIES = new Set(['@fastify/rate-limit', '@formancy/spec', 'fastify', 'jose', 'mssql', 'pino', 'postgres', 'tedious'])

/** What a disturbance counter is called on the page. */
const DISTURBANCES: Readonly<Record<string, string>> = { autovacuum: 'autovacuum', autoanalyze: 'autoanalyze', recompiles: 'recompiles', statisticsUpdated: 'statistics updated' }

function labelOf(scenario: CatalogueScenario): string {
  return scenario.form === 'order-unfiltered' ? `${scenario.label} (no tenant row filter)` : scenario.label
}

function rowsRead(scenario: CatalogueScenario): string {
  if (scenario.rowsRead === null) return '—'
  return 'exactly' in scenario.rowsRead ? grouped(scenario.rowsRead.exactly) : `at most ${grouped(scenario.rowsRead.atMost)}`
}

function byRound(rounds: ReadonlyArray<number | null>): string {
  if (rounds.some((value) => value === null)) return 'n too small'
  const values = rounds as number[]
  return `${figure(Math.min(...values))}–${figure(Math.max(...values))}`
}

function scenarioRows(results: Results, engine: EngineKey, concurrency: number): Array<{ scenario: CatalogueScenario; entry: ScenarioResult }> {
  const found: Array<{ scenario: CatalogueScenario; entry: ScenarioResult }> = []
  for (const scenario of results.catalogue.scenarios) {
    const entry = results.scenarios.find((candidate) => candidate.engine === engine && candidate.scenario === scenario.name && candidate.concurrency === concurrency)
    if (entry !== undefined) found.push({ scenario, entry })
  }
  return found
}

function whenAndOnWhat(results: Results): string {
  const { machine, network, server, engines } = results
  const { cpu } = machine
  const topology = `${grouped(cpu.sockets)} socket × ${grouped(cpu.coresPerSocket)} cores × ${grouped(cpu.threadsPerCore)} thread`
  const presented =
    cpu.hypervisor === null
      ? `${grouped(cpu.vcpus)} CPUs as ${topology}`
      : `${grouped(cpu.vcpus)} vCPUs presented by the ${cpu.hypervisor} hypervisor as ${topology}; the host's topology is not visible`
  const limits = (engine: EngineKey): string => {
    const limit = machine.databaseLimits[engine]
    const parts = [limit.nanoCpus > 0 ? `${figure(limit.nanoCpus / 1e9)} CPUs` : '', limit.cpuQuota > 0 ? `CPU quota ${grouped(limit.cpuQuota)}/${grouped(limit.cpuPeriod)} µs` : '', limit.memoryBytes > 0 ? `memory ${bytes(limit.memoryBytes)}` : '']
    const set = parts.filter((part) => part !== '')
    return `${ENGINE_NAMES[engine]} ${set.length === 0 ? 'none' : set.join(', ')}`
  }
  const proxies = Object.entries(network.client.proxy)
    .map(([name, value]) => `${name} ${value === null ? 'unset' : `\`${value}\``}`)
    .join(', ')
  const reach = (engine: EngineKey): string => {
    const entry = network.engines[engine]
    return `${ENGINE_NAMES[engine]} at \`${entry.host}\` (resolved in the order ${entry.lookup.map((address) => `\`${address}\``).join(', ')}), port ${String(entry.port)}, ${entry.dockerProxy ? 'through docker-proxy' : 'with no docker-proxy process found for the port'}, no TLS`
  }
  const quiet = machine.quiet
  const lines = [
    `- **When:** from ${results.measuredAt} to ${results.finishedAt}, ${figure(results.durationSeconds)} s. Commit \`${results.commit.slice(0, 12)}\`, product digest \`${productDigest(results.product)}\`.`,
    `- **Machine:** ${cpu.model}; ${presented}. Memory ${bytes(machine.memoryBytes)}. ${machine.os.prettyName}, kernel ${machine.os.kernel}, ${grouped(machine.os.clkTck)} clock ticks a second. The harness in cgroup \`${machine.cgroup.path}\`, \`cpu.max\` \`${machine.cgroup.cpuMax}\`. Database container limits: ${ENGINE_KEYS.map(limits).join('; ')}.`,
    `- **Docker** ${machine.docker.version} on ${machine.docker.os}, storage driver ${machine.docker.storageDriver}, cgroup driver ${machine.docker.cgroupDriver}, ${grouped(machine.docker.ncpu)} CPUs, ${bytes(machine.docker.memTotalBytes)}. **Node** ${machine.node}.`,
    `- **Network:** the client sends ${network.client.transport} to \`${network.client.address}\`, no TLS; ${proxies}. ${ENGINE_KEYS.map(reach).join('; ')}. The added-latency block holds every database answer ${setting(network.hopDelayMs)} ms in a TCP hop.`,
    `- **Server:** \`${server.entry}\` under Node ${server.node}, configured by ${server.settings.map((name) => `\`${name}\``).join(', ')}; rate limit ${setting(server.rateLimit)} a minute; logger ${server.logger ? 'on' : 'off'}; audit ${server.auditKeyed ? 'on, records named by a keyed hash' : 'on, no records named'}. Account: ${ENGINE_KEYS.map((engine) => `\`${server.account[engine]}\` on ${ENGINE_NAMES[engine]}`).join(', ')}.`,
    `- **Quiet check${quiet.enforced ? '' : ', recorded and not enforced'}:** ${quiet.containersBefore.length === 0 ? 'no other container running' : `running before: ${quiet.containersBefore.join(', ')}`}; load average ${figure(quiet.loadAverage)}; busiest second ${figure(quiet.busyVcpusMax)} vCPUs; steal ${quiet.stealReported ? 'reported by this hypervisor' : 'not reported by this hypervisor'}; calibration baseline ${figure(quiet.calibrationBaselineMs)} ms; over ${setting(quiet.seconds)} s.`,
  ]
  const images = table(
    ['Engine', 'Image', 'Image id', 'Digests', 'Version', 'Text order', 'Settings'],
    ENGINE_KEYS.map((engine) => {
      const facts = engines[engine]
      const text = facts.text === null ? 'the collation in Settings' : facts.text.codePointOrder ? `code-point order${facts.version.includes('musl') ? ' (musl)' : ''}` : 'locale order'
      const settings = Object.entries(facts.settings)
        .map(([name, value]) => `${name} ${value}`)
        .join(', ')
      return [ENGINE_NAMES[engine], `\`${facts.image}\``, `\`${facts.imageId}\``, facts.repoDigests.map((digest) => `\`${digest}\``).join(' '), facts.version, text, settings]
    }),
  )
  const packages = Object.entries(results.product.packages).sort(([a], [b]) => (a < b ? -1 : 1))
  const named = packages.filter(([name]) => NAMED_LIBRARIES.has(name)).map(([name, version]) => `\`${name}@${version}\``)
  const others = packages.length - named.length
  const libraries = `${named.join(', ')}${others === 0 ? '' : `, and ${grouped(others)} other packages`}`
  return [`### When and on what`, '', ...lines, '', images, '', `Drivers and server libraries as installed: ${libraries} in the server's and the client's runtime closure, each version in \`results.json\`.`].join('\n')
}

function sizes(results: Results): string {
  const size = (engine: EngineKey): string[] => {
    const { before, after } = results.engines[engine].sizes
    const tenants = Object.entries(after.customerRows.perTenant)
      .sort(([a], [b]) => Number(a) - Number(b))
      .map(([tenant, rows]) => `${grouped(rows)} in tenant ${tenant}`)
      .join(', ')
    const span = (from: SizeFacts, to: SizeFacts, pick: (facts: SizeFacts) => number, show: (value: number) => string): string => `${show(pick(from))} → ${show(pick(to))}`
    return [
      ENGINE_NAMES[engine],
      `${grouped(after.customerRows.total)} (${tenants})`,
      bytes(after.customerDataBytes),
      bytes(after.customerIndexBytes),
      span(before, after, (facts) => facts.orderRows, grouped),
      span(before, after, (facts) => facts.databaseBytes, bytes),
    ]
  }
  const bundle = table(
    ['Form', 'Version file', 'Its snapshot', 'Snapshot objects'],
    Object.entries(results.bundle)
      .sort(([a], [b]) => (a < b ? -1 : 1))
      .map(([form, facts]) => [`\`${form}\``, bytes(facts.versionBytes), bytes(facts.snapshotBytes), grouped(facts.snapshotObjects)]),
  )
  const sized = results.sizedTable
  return [
    '### Database size',
    '',
    `\`sales.customer\` holds the generator's \`${sized.generator}\` (digest \`${sized.digest.slice(0, 12)}\`), loaded in ${ENGINE_KEYS.map((engine) => `${figure(sized.loadSeconds[engine])} s on ${ENGINE_NAMES[engine]}`).join(' and ')}. The measured clerk is tenant 1.`,
    '',
    table(['Engine', '`sales.customer` rows', 'Customer data', 'Customer indexes', '`sales.order` rows, start → end', 'Database, start → end'], ENGINE_KEYS.map(size)),
    '',
    bundle,
  ].join('\n')
}

function method(results: Results): string {
  const p = results.protocol
  const budget = (b: { requests: number; seconds: number; atLeast: number }): string => `up to ${setting(b.requests)} requests or ${setting(b.seconds)} s, whichever ends first, and at least ${setting(b.atLeast)}`
  const tolerance = p.calibration.tolerance === null ? 'none set' : p.calibration.tolerance === 'unbounded' ? 'unbounded' : setting(p.calibration.tolerance)
  return [
    '### How it was measured',
    '',
    `- Protocol \`${p.name}\`: ${setting(p.rounds)} rounds, engine order alternating; in each, every block warms up with ${budget(p.warmup)}, then takes ${budget(p.samples)}.`,
    `- Closed loop at ${p.concurrency.map((c) => setting(c)).join(' and ')} in flight: a request starts when one finishes, so a slow answer delays the next and no arrival rate is modelled.`,
    `- A sample is the time from the client call to its parsed answer. Percentiles ${p.percentiles.map((q) => `p${String(q)}`).join(', ')} by nearest rank over every round's samples, printed only when at least ten samples sit at or above the rank, otherwise "n too small".`,
    `- Added latency: ${setting(p.latency.delayMs)} ms on every database answer, through a TCP hop, one request at a time, ${setting(p.latency.samples)} samples per pass, undelayed first. The difference is the median of the rounds' differences of p50s.`,
    `- In-process components: ${setting(p.components.warmup)} warm-up and ${setting(p.components.samples)} samples each.`,
    `- Before each block's warm-up and after its timed window, an idle gap of ${setting(p.calibration.gapMs)} ms with nothing in flight. Calibration: a fixed CPU-bound workload every ${setting(p.calibration.intervalMs)} ms on a worker thread, read only in the gaps, because it slows under the run's own load too; a block with a gap whose median ran past ${tolerance} times the quiet baseline is run again once, and a second miss refuses the run. Contention during a block's own load is not seen.`,
    `- Database CPU per request is the database container's CPU over the timed window less its CPU per second in the gaps times the window's seconds, over the requests; what the engine did on its own during the window alone is in it. None is printed for a request that makes no round trip.`,
    `- Disturbances, read by the database's owner between blocks: PostgreSQL's autovacuum and autoanalyze runs on any table of the database, SQL Server's recompilations and statistics updated on any user table.`,
  ].join('\n')
}

/**
 * The database's CPU per request with its idle rate taken off: the
 * container's CPU over the block, less what it used per second in the idle
 * gaps around it times the block's seconds, over the requests. None for a
 * request that makes no round trip, which would only print the engine's own
 * work as if a request had caused it; the idle rate beside it says what that is.
 */
function databaseCpu(entry: ScenarioResult): [string, string] {
  const perRequest = entry.roundTrips === 0 ? '—' : figure(entry.databaseCpuMsPerRequest - entry.databaseIdleCpuMsPerSecond / entry.throughput)
  return [perRequest, figure(entry.databaseIdleCpuMsPerSecond)]
}

const DATABASE_CPU = ['Database CPU per request, idle rate taken off (ms)', 'Database CPU when idle (ms a second)'] as const

function oneAtATime(results: Results, engine: EngineKey): string {
  const rows = scenarioRows(results, engine, 1).map(({ scenario, entry }) => [
    labelOf(scenario),
    rowsRead(scenario),
    grouped(entry.rowsAnswered),
    grouped(entry.roundTrips),
    grouped(entry.n),
    cell(entry.p50),
    cell(entry.p90),
    cell(entry.p99),
    figure(entry.max),
    byRound(entry.rounds),
    figure(entry.serverCpuMsPerRequest),
    ...databaseCpu(entry),
  ])
  return [
    `### One request at a time: ${ENGINE_NAMES[engine]}`,
    '',
    table(['Operation', 'Rows the database reads', 'Rows answered', 'Database round trips', 'n', 'p50 (ms)', 'p90 (ms)', 'p99 (ms)', 'max (ms)', 'p50 by round (ms)', 'Server CPU per request (ms)', ...DATABASE_CPU], rows),
  ].join('\n')
}

function inFlight(results: Results, engine: EngineKey, concurrency: number): string {
  const rows = scenarioRows(results, engine, concurrency).map(({ scenario, entry }) => [
    labelOf(scenario),
    grouped(entry.n),
    figure(entry.throughput),
    cell(entry.p50),
    cell(entry.p90),
    cell(entry.p99),
    figure(entry.max),
    figure(entry.serverCpuMsPerRequest),
    ...databaseCpu(entry),
  ])
  return [
    `### ${grouped(concurrency)} in flight: ${ENGINE_NAMES[engine]}`,
    '',
    table(['Operation', 'n', 'Requests per second', 'p50 (ms)', 'p90 (ms)', 'p99 (ms)', 'max (ms)', 'Server CPU per request (ms)', ...DATABASE_CPU], rows),
  ].join('\n')
}

function addedLatency(results: Results, engine: EngineKey): string {
  const delay = setting(results.protocol.latency.delayMs)
  const rows = results.catalogue.scenarios.flatMap((scenario) => {
    const entry: LatencyResult | undefined = results.latency.find((candidate) => candidate.engine === engine && candidate.scenario === scenario.name)
    if (entry === undefined) return []
    // The same request sent directly, one at a time: the hop undelayed beside it shows what the hop costs by itself.
    const direct = results.scenarios.find((candidate) => candidate.engine === engine && candidate.scenario === scenario.name && candidate.concurrency === 1)
    return [[labelOf(scenario), grouped(entry.roundTrips), direct === undefined ? '—' : cell(direct.p50), cell(entry.undelayedMs), cell(entry.delayedMs), cell(entry.differenceMs), figure(entry.expectedMs), entry.ratio === null ? '—' : figure(entry.ratio)]]
  })
  return [
    `### Added database latency: ${ENGINE_NAMES[engine]}`,
    '',
    table(['Operation', 'Database round trips', 'p50 direct (ms)', 'p50 through the hop, undelayed (ms)', `p50 with ${delay} ms per answer (ms)`, 'Difference (ms)', `${delay} ms × round trips`, 'Ratio'], rows),
  ].join('\n')
}

/** What a request the server refuses still asks the database, per engine, counted through the hop; no time is taken of a refusal. */
function refused(results: Results): string {
  const rows = results.catalogue.refusals.map((refusal) => [
    refusal.label,
    `${String(refusal.answer.status)} \`${refusal.answer.code}\``,
    ...ENGINE_KEYS.map((engine) => {
      const entry = results.refusals.find((candidate) => candidate.engine === engine && candidate.scenario === refusal.name)
      return entry === undefined ? '—' : grouped(entry.roundTrips)
    }),
  ])
  return [
    '### Refused, counted and never timed',
    '',
    'Each counted once through the hop after one request to warm it, its answer checked; a refusal is not timed.',
    '',
    table(['Operation', 'Answer', ...ENGINE_KEYS.map((engine) => `Database round trips, ${ENGINE_NAMES[engine]}`)], rows),
  ].join('\n')
}

function fixedCosts(results: Results): string {
  const { components } = results
  const summary = (s: { n: number; p50: number | null; p90: number | null; p99: number | null; max: number }): string[] => [grouped(s.n), cell(s.p50), cell(s.p90), cell(s.p99), figure(s.max)]
  const rows: string[][] = [[components.verifyToken.label, ...summary(components.verifyToken), '']]
  for (const engine of ENGINE_KEYS) {
    const read = components.readBundle[engine]
    const facts = results.bundle[read.form]
    rows.push([`${read.label}, \`${read.form}\``, ...summary(read), facts === undefined ? '' : `a ${bytes(facts.versionBytes)} version, its snapshot ${bytes(facts.snapshotBytes)} in ${grouped(facts.snapshotObjects)} objects`])
  }
  for (const engine of ENGINE_KEYS) {
    const health = results.scenarios.find((entry) => entry.engine === engine && entry.scenario === 'health' && entry.concurrency === 1)
    if (health !== undefined) rows.push([`\`GET /health\` over loopback, ${ENGINE_NAMES[engine]} rounds`, ...summary(health), 'as in the one-at-a-time table'])
  }
  for (const engine of ENGINE_KEYS) {
    const floor = components.floor[engine]
    rows.push([`${results.catalogue.floor.label}, ${ENGINE_NAMES[engine]}`, ...summary(floor), `${grouped(floor.roundTrips)} round trips: ${floor.perRoundTripMs === null ? 'n too small' : `${figure(floor.perRoundTripMs)} ms each at p50`}`])
  }
  return ['### Fixed costs', '', table(['Component', 'n', 'p50 (ms)', 'p90 (ms)', 'p99 (ms)', 'max (ms)', 'Beside it'], rows)].join('\n')
}

function runFacts(entries: readonly RunFacts[]): string[] {
  const mean = entries.reduce((sum, entry) => sum + entry.machineBusyPct, 0) / entries.length
  const steals = entries.map((entry) => entry.steal)
  const steal = steals.every((value) => value === 'not reported') ? 'not reported' : figure(Math.max(...steals.map((value) => (value === 'not reported' ? 0 : value))))
  const disturbances: Record<string, number> = {}
  for (const entry of entries) for (const [name, count] of Object.entries(entry.disturbances)) disturbances[name] = (disturbances[name] ?? 0) + count
  return [
    figure(mean),
    steal,
    figure(Math.max(...entries.map((entry) => entry.generatorLagP99Ms))),
    figure(Math.max(...entries.map((entry) => entry.calibrationRatio))),
    entries.some((entry) => entry.repeated) ? 'yes' : 'no',
    Object.entries(disturbances)
      .map(([name, count]) => `${DISTURBANCES[name] ?? name} ${grouped(count)}`)
      .join(', '),
    grouped(entries.reduce((sum, entry) => sum + entry.reconnects, 0)),
  ]
}

function theRun(results: Results): string {
  const rows: string[][] = []
  for (const engine of ENGINE_KEYS) {
    for (const concurrency of results.protocol.concurrency) {
      const entries = results.scenarios.filter((entry) => entry.engine === engine && entry.concurrency === concurrency).map((entry) => entry.run)
      if (entries.length > 0) rows.push([ENGINE_NAMES[engine], `${grouped(concurrency)} in flight`, ...runFacts(entries)])
    }
    const latency = results.latency.filter((entry) => entry.engine === engine).map((entry) => entry.run)
    if (latency.length > 0) rows.push([ENGINE_NAMES[engine], 'added latency', ...runFacts(latency)])
  }
  const sent = results.checks.requests.reduce((sum, row) => sum + row.count, 0)
  const events = results.checks.runtimeEvents.reduce((sum, row) => sum + row.count, 0)
  return [
    '### The run',
    '',
    table(['Engine', 'Block', 'Machine busy, mean (%)', 'Steal, most (%)', 'Generator lag p99, worst (ms)', 'Calibration, worst idle gap against the baseline', 'Repeated', 'Disturbances', 'Reconnects'], rows),
    '',
    `The server wrote ${figure(results.server.logLinesPerRequest)} log lines per runtime request. Its log holds ${grouped(events)} runtime audit events for the ${grouped(sent)} runtime requests the harness sent, equal by operation, form and status, and ${grouped(results.checks.adminEvents)} administrator events for ${grouped(results.checks.adminRequests)} requests. ${grouped(results.checks.writes)} creates and updates were sent, all through one server's write-id cache (0031); that is a count, not a claim about the cache's bound. The run's orders reference ${ENGINE_KEYS.map((engine) => `${grouped(results.checks.createdCustomers[engine])} customers on ${ENGINE_NAMES[engine]}`).join(' and ')}: creates rotate through them, so no one customer's row is locked by every create.`,
  ].join('\n')
}

/** The region between the markers, without them. */
export function renderPerformance(results: Results): string {
  const parts = [whenAndOnWhat(results), sizes(results), method(results)]
  for (const engine of ENGINE_KEYS) parts.push(oneAtATime(results, engine))
  for (const concurrency of results.protocol.concurrency.filter((c) => c !== 1)) for (const engine of ENGINE_KEYS) parts.push(inFlight(results, engine, concurrency))
  for (const engine of ENGINE_KEYS) parts.push(addedLatency(results, engine))
  parts.push(refused(results), fixedCosts(results), theRun(results))
  return `${parts.join('\n\n')}\n`
}

/**
 * `page` with its region replaced by `region`, opened by `START_MARKER`
 * whether it was rendered before or never was; refuses a page without an
 * opening and a closing marker, in order.
 */
export function replaceGenerated(page: string, region: string): string {
  const opening = page.includes(START_MARKER) ? START_MARKER : UNMEASURED_MARKER
  const start = page.indexOf(opening)
  const end = page.indexOf(END_MARKER)
  if (start === -1 || end === -1 || end < start) throw new Error('the page needs both generated-region markers, start before end')
  const body = region.endsWith('\n') ? region : `${region}\n`
  return `${page.slice(0, start)}${START_MARKER}\n${body}${page.slice(end)}`
}
