import { useMemo } from 'react'
import type { ReactElement } from 'react'
import type { DatabaseKind, FieldBinding } from '@formancy/data-core'
import type { OptionsSources } from '@formancy/react'
import { previewEngine } from './engines.js'
import { generateExamples } from './examples.js'
import type { Example } from './examples.js'
import { CAPTURED, capturedRows, lookupSources } from './lookup-source.js'
import type { CapturedTable } from './lookup-source.js'
import { GenerationNotes } from './notes.js'
import { AngularPane, ReactPane } from './panes.js'
import { FIXTURE_SNAPSHOT } from './snapshot.js'

/** How a database kind is written for a person. */
const ENGINE_NAMES: Readonly<Record<DatabaseKind, string>> = { postgres: 'PostgreSQL', sqlserver: 'SQL Server' }

type LookupBinding = Extract<FieldBinding, { kind: 'lookup' }>

function tableOf(example: Example): string {
  return `${example.request.root.schema}.${example.request.root.name}`
}

/**
 * Where a lookup's options come from, said beside the form that has one.
 *
 * The source is in memory, because this page has no server, and a page that
 * did not say so would pass its captured rows off as a lookup. A host gets the
 * list from the runtime plane, which apps/host shows (0029). The row count is
 * counted, not written.
 */
function LookupNote({
  example,
  binding,
  captured,
}: {
  example: Example
  binding: LookupBinding
  captured: readonly CapturedTable[]
}): ReactElement {
  const label = example.generated.form.model.fields.find((field) => field.key === binding.field)?.label ?? binding.field
  const rows = capturedRows(captured, binding.target.table)
  return (
    <p role="note" className="lookup-note">
      {rows === undefined ? (
        <>
          The <strong>{String(label)}</strong> list has no source on this page, so both renderers say so where the
          chooser would be.
        </>
      ) : (
        <>
          The <strong>{String(label)}</strong> list is held in memory, because this page has no server:{' '}
          {rows.length} {binding.target.table.name} rows captured with the snapshot, each offered under the key token
          the server decodes. A host gets the list from the server&rsquo;s runtime plane through{' '}
          <code>@formancy/data-client</code>, as apps/host shows.
        </>
      )}
    </p>
  )
}

/** One generated form: its notes, and the document under both renderers. */
function ExampleSection({
  example,
  sources,
  captured,
}: {
  example: Example
  sources: OptionsSources
  captured: readonly CapturedTable[]
}): ReactElement {
  const { request, generated } = example
  const table = tableOf(example)
  const tableId = `form-${generated.form.id}`
  const engines = useMemo(
    () => ({ react: previewEngine(generated.form, 'react'), angular: previewEngine(generated.form, 'angular') }),
    [generated.form],
  )
  const lookups = generated.bindings.fields.filter((binding): binding is LookupBinding => binding.kind === 'lookup')

  return (
    <section className="example" aria-labelledby={tableId}>
      <div className="example-head">
        <h2 id={tableId}>{table}</h2>
        <p>
          Generated as <q>{request.title}</q>, form id <code>{generated.form.id}</code>.
        </p>
      </div>
      {lookups.map((binding) => (
        <LookupNote key={binding.field} example={example} binding={binding} captured={captured} />
      ))}
      <div className="example-grid">
        <GenerationNotes generated={generated} tableId={tableId} />
        <ReactPane tableId={tableId} table={table} engine={engines.react} sources={sources} />
        <AngularPane tableId={tableId} table={table} engine={engines.angular} sources={sources} />
      </div>
    </section>
  )
}

/**
 * Generated forms, in both renderers.
 *
 * Everything below the header is computed here, in the browser: the snapshot
 * is checked, `generateForm` runs over it, and each document is rendered by
 * `@formancy/react` and by `@formancy/angular` side by side, with the
 * generator's notes beside them.
 *
 * `captured` is the rows the lookup sources are built from: the ones captured
 * with the snapshot unless a caller says otherwise, which is how a test shows
 * what the page does for a lookup with no rows at all.
 */
export function App({ captured = CAPTURED }: { captured?: readonly CapturedTable[] }): ReactElement {
  const examples = useMemo(() => generateExamples(FIXTURE_SNAPSHOT), [])
  const sources = useMemo(() => lookupSources(examples, captured), [examples, captured])

  return (
    <div className="page">
      <a className="skip" href="#forms">
        Skip to the forms
      </a>
      <header className="masthead">
        <p className="eyebrow">Formancy Data &middot; examples</p>
        <h1>Generated forms, in both renderers</h1>
        <p className="lead">
          Each form below is generated by <code>generateForm</code> in this browser, from a snapshot of the shared
          fixture captured from {ENGINE_NAMES[FIXTURE_SNAPSHOT.kind]} {FIXTURE_SNAPSHOT.serverVersion}. Each renders
          twice, over the same document: with <code>@formancy/react</code> and with <code>@formancy/angular</code>.
        </p>
        <nav aria-label="Forms on this page">
          <ul>
            {examples.map((example) => (
              <li key={example.generated.form.id}>
                <a href={`#form-${example.generated.form.id}`}>{tableOf(example)}</a>
              </li>
            ))}
          </ul>
        </nav>
      </header>

      <main id="forms" tabIndex={-1}>
        {examples.map((example) => (
          <ExampleSection key={example.generated.form.id} example={example} sources={sources} captured={captured} />
        ))}
      </main>

      <footer className="colophon">
        <p>
          Nothing on this page saves. <strong>Validate</strong> runs the formancy engine in your browser, and there is no
          server behind it yet.
        </p>
        <p>
          Formancy Data is source-available, not open source. The formancy packages it renders with are Apache-2.0.
        </p>
      </footer>
    </div>
  )
}
