// README.md's pictures, written where they are generated, and the repository
// guard's checks of them (0038).
//
// Two jobs, both pure over what `repository()` reads, so readme.test.mjs runs
// them in `pnpm test:repo` without a browser:
//
// - **Render.** README.md carries one generated region per placement: `hero`
//   for the hero scene, and one per app for the rest, in scenes.json's
//   order. An `inline` or `hero` scene is its picture at its recorded CSS
//   width and its italic caption, a studio scene's led by its step; each run
//   of consecutive `more` scenes is one <details> whose summary is derived
//   from their titles. `node scripts/pictures/readme.mjs --write` writes the
//   regions; nothing else does.
// - **Check.** Each function below returns the sentences that are wrong with
//   the repository, empty when nothing is: the regions are the render, every
//   scene has its picture and the bytes match, nothing else is in the
//   pictures' directory, every caption quotes only what its parts say, one
//   look, every link and picture the regions show resolves, the scenes'
//   shape, and a guard on the guard.

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describeLook, IMAGES, misquotes, pictureOf, readRecord, readScenes, REPO, serialize, undecodable } from './record.mjs'

export const README = join(REPO, 'README.md')

const PLACEMENTS = ['hero', 'inline', 'more']
export const START = (name) => `<!-- generated by scripts/pictures/readme.mjs from scripts/pictures/scenes.json and docs/images/readme/captured.json: ${name}; do not edit -->`
export const END = '<!-- end generated -->'
/** Any of this file's markers, whatever region it names. */
const ANY_START = /<!-- generated by scripts\/pictures\/readme\.mjs from [^>]*: ([^;>]*); do not edit -->/g

/** The sentence the hero region ends with. */
export const HERO_LINE =
  'Every picture in this README is taken by `pnpm pictures` from the built pages and the real data server, and the browser job fails when one of them shows text the page no longer shows ([how, and what nothing checks](./docs/images/README.md)).'

/** The region a scene is drawn in: the hero's own, or its app's. */
const regionOf = (scene) => (scene.placement === 'hero' ? 'hero' : scene.app)

/** The regions README.md must carry, in scenes.json's order: derived, so an app given scenes is given a region. */
export const regionNames = (scenes) => [...new Set(scenes.map(regionOf))]

/** `"8. Drift"` as the caption's lead, `**Step 8, Drift.**`. */
function lead(step) {
  const [, number, name] = /^(\d+)\.\s+(.+)$/.exec(step) ?? []
  if (number === undefined) throw new Error(`the step "${step}" is not "<number>. <name>"`)
  return `**Step ${number}, ${name}.** `
}

const attribute = (text) => text.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')

/** One scene as README.md shows it: the picture at its recorded CSS width, then its caption. */
function picture(scene, record) {
  const entry = record[scene.id]
  if (entry === undefined) throw new Error(`${scene.id} has no record in docs/images/readme/captured.json: \`pnpm pictures --scene ${scene.id}\` takes it`)
  return [`<img src="./${pictureOf(scene.id)}" width="${String(entry.css.width)}" alt="${attribute(scene.alt)}">`, '', `${scene.step === undefined ? '' : lead(scene.step)}*${scene.caption}*`].join('\n')
}

/** Every generated region's text, by name, from scenes.json and the record. */
export function render(scenes, record) {
  const rendered = {}
  for (const name of regionNames(scenes)) {
    const blocks = []
    let more = []
    const close = () => {
      if (more.length === 0) return
      blocks.push(['<details>', `<summary>More: ${more.map((scene) => scene.title).join(', ')}</summary>`, '', ...more.map((scene) => picture(scene, record)).join('\n\n').split('\n'), '', '</details>'].join('\n'))
      more = []
    }
    for (const scene of scenes.filter((candidate) => regionOf(candidate) === name)) {
      if (scene.placement === 'more') {
        more.push(scene)
        continue
      }
      close()
      blocks.push(picture(scene, record))
    }
    close()
    if (name === 'hero') blocks.push(HERO_LINE)
    rendered[name] = blocks.join('\n\n')
  }
  return rendered
}

/** The generated regions of `markdown`, by name; throws when one is repeated or unclosed. */
export function generatedRegions(markdown) {
  const text = markdown.replaceAll('\r\n', '\n')
  const found = {}
  for (const match of text.matchAll(ANY_START)) {
    const [marker, name] = match
    if (Object.hasOwn(found, name)) throw new Error(`README.md holds the pictures region "${name}" twice`)
    const from = match.index + marker.length
    const end = text.indexOf(END, from)
    const next = text.slice(from).search(ANY_START)
    if (end === -1 || (next !== -1 && from + next < end)) throw new Error(`README.md: the pictures region "${name}" is never closed by ${END}`)
    found[name] = text.slice(from, end).trim()
  }
  return found
}

/** `markdown` with every generated region replaced by what `render` gives; throws when a region is missing or one is not this render's. */
export function rewrite(markdown, scenes, record) {
  let text = markdown.replaceAll('\r\n', '\n')
  const present = Object.keys(generatedRegions(text))
  const names = regionNames(scenes)
  const missing = names.filter((name) => !present.includes(name))
  const stray = present.filter((name) => !names.includes(name))
  if (missing.length > 0 || stray.length > 0) {
    throw new Error(`README.md must hold the pictures regions ${names.join(', ')}, each opened by ${START('<name>')}${missing.length > 0 ? `; ${missing.join(', ')} missing` : ''}${stray.length > 0 ? `; ${stray.join(', ')} no scene's` : ''}`)
  }
  const rendered = render(scenes, record)
  for (const name of names) {
    const start = text.indexOf(START(name)) + START(name).length
    const end = text.indexOf(END, start)
    // Blank lines around, so Markdown reads the HTML and the captions as blocks of their own.
    text = `${text.slice(0, start)}\n\n${rendered[name]}\n\n${text.slice(end)}`
  }
  return text
}

/** What the checks read, from the working tree. */
export function repository() {
  const scenes = readScenes()
  const recordText = existsSync(join(IMAGES, 'captured.json')) ? readFileSync(join(IMAGES, 'captured.json'), 'utf8') : undefined
  return {
    scenes,
    record: recordText === undefined ? {} : JSON.parse(recordText),
    recordText,
    readme: readFileSync(README, 'utf8'),
    listing: existsSync(IMAGES) ? readdirSync(IMAGES) : [],
    file: (path) => (existsSync(join(REPO, path)) ? readFileSync(join(REPO, path)) : undefined),
    exists: (path) => existsSync(join(REPO, path)),
    appScripts: readdirSync(join(REPO, 'apps')).filter((app) => existsSync(join(REPO, 'apps', app, 'scripts', 'pictures.mjs'))),
  }
}

/** The regions equal the render; each region appears once and no other pictures region exists. */
export function regionProblems({ scenes, record, readme }) {
  let present
  try {
    present = generatedRegions(readme)
  } catch (error) {
    return [error.message]
  }
  const names = regionNames(scenes)
  const problems = []
  for (const name of Object.keys(present)) if (!names.includes(name)) problems.push(`README.md holds a pictures region "${name}" no scene is drawn in`)
  for (const name of names) if (!Object.hasOwn(present, name)) problems.push(`README.md does not hold the pictures region "${name}", opened by ${START(name)}`)
  let rendered
  try {
    rendered = render(scenes, record)
  } catch (error) {
    return [...problems, error.message]
  }
  for (const name of names) {
    if (Object.hasOwn(present, name) && present[name] !== rendered[name]) problems.push(`README.md's pictures region "${name}" is not what scenes.json and captured.json render: run \`node scripts/pictures/readme.mjs --write\``)
  }
  return problems
}

/** Every scene has a record, and a picture whose bytes and sha256 are the record's; captured.json is as the camera writes it. */
export function integrityProblems({ scenes, record, recordText, file }) {
  if (recordText === undefined) return ['docs/images/readme/captured.json does not exist: `pnpm pictures --all` takes the pictures and writes it']
  const problems = []
  if (recordText !== serialize(record, scenes)) problems.push('docs/images/readme/captured.json is not as the camera writes it: pretty-printed, keyed in scenes.json order, LF only')
  for (const scene of scenes) {
    const entry = record[scene.id]
    if (entry === undefined) {
      problems.push(`${scene.id} has no record: \`pnpm pictures --scene ${scene.id}\` takes it`)
      continue
    }
    if (entry.file !== pictureOf(scene.id)) problems.push(`${scene.id}'s record names ${String(entry.file)}, not ${pictureOf(scene.id)}`)
    const bytes = file(pictureOf(scene.id))
    if (bytes === undefined) {
      problems.push(`${pictureOf(scene.id)} does not exist, and its record says it was taken`)
      continue
    }
    if (bytes.length !== entry.bytes || createHash('sha256').update(bytes).digest('hex') !== entry.sha256) {
      problems.push(`${pictureOf(scene.id)} is not the picture its record describes (${String(bytes.length)} bytes, recorded ${String(entry.bytes)}): it was changed by hand, or the record was`)
    }
  }
  return problems
}

/** The pictures' directory holds nothing but the record and the scenes' pictures, and the record nothing but scenes. */
export function orphanProblems({ scenes, record, listing }) {
  const wanted = new Set(['captured.json', ...scenes.map((scene) => `${scene.id}.webp`)])
  return [
    ...listing.filter((name) => !wanted.has(name)).map((name) => `docs/images/readme/${name} is no scene's picture`),
    ...Object.keys(record).filter((id) => !scenes.some((scene) => scene.id === id)).map((id) => `captured.json records ${id}, which is no scene of scenes.json`),
  ]
}

/** Every quote is listed and occurs in each part it names, and every recorded line decodes. */
export function quoteProblems({ scenes, record }) {
  const problems = []
  for (const scene of scenes) {
    const text = record[scene.id]?.text
    if (text !== undefined) problems.push(...undecodable(scene.id, text))
    // A scene without a record is held to its keys only; integrityProblems says it has no record.
    problems.push(...misquotes(scene, text))
  }
  return problems
}

/** Every record was taken on the same look. */
export function lookProblems({ record }) {
  const looks = [...new Set(Object.values(record).map((entry) => describeLook(entry.look)))]
  return looks.length <= 1 ? [] : [`the pictures were taken on ${String(looks.length)} looks, and every one must be taken on one: ${looks.join('; ')}; \`pnpm pictures --all\` retakes every picture`]
}

/** Every relative link and picture source in `markdown`: a Markdown link's target, and an `src="…"`. */
function relativeTargets(markdown) {
  return [...markdown.matchAll(/\]\(([^)\s]+)\)|\bsrc="([^"]+)"/g)].map((match) => match[1] ?? match[2]).filter((target) => !/^[a-z]+:/i.test(target) && !target.startsWith('#'))
}

/**
 * Every relative link and picture in README.md's generated regions names a
 * file that exists: a caption's, said by its scene, and what the render
 * writes itself -- the hero line's link to the recipe, and every <img> --
 * said by its region. A render that cannot be drawn is guardProblems' to say.
 */
export function linkProblems({ scenes, record, exists }) {
  const missing = (target) => !exists(target.split('#')[0].replace(/^\.\//, ''))
  const problems = []
  const inCaptions = new Set()
  for (const scene of scenes) {
    for (const target of relativeTargets(scene.caption ?? '')) {
      inCaptions.add(target)
      if (missing(target)) problems.push(`${scene.id}'s caption links ${target}, which is no file of the repository`)
    }
  }
  let rendered = {}
  try {
    rendered = render(scenes, record ?? {})
  } catch {
    // guardProblems says the regions could not be rendered.
  }
  for (const [name, text] of Object.entries(rendered)) {
    for (const target of new Set(relativeTargets(text))) {
      if (!inCaptions.has(target) && missing(target)) problems.push(`README.md's pictures region "${name}" links ${target}, which is no file of the repository`)
    }
  }
  return problems
}

/** The scenes' shape: ids, apps, placements, the texts, steps, and an app script for every app. */
export function shapeProblems({ scenes, appScripts }) {
  const problems = []
  const seen = new Set()
  for (const scene of scenes) {
    const id = String(scene.id)
    if (!/^[a-z0-9-]+$/.test(id)) problems.push(`the scene id ${JSON.stringify(scene.id)} is not [a-z0-9-]+`)
    if (seen.has(id)) problems.push(`the scene id ${id} is used twice`)
    seen.add(id)
    if (!PLACEMENTS.includes(scene.placement)) problems.push(`${id}: placement ${JSON.stringify(scene.placement)} is none of ${PLACEMENTS.join(', ')}`)
    for (const key of ['title', 'caption', 'alt']) if (typeof scene[key] !== 'string' || scene[key].trim() === '') problems.push(`${id} has no ${key}`)
    if (scene.placement === 'more' && typeof scene.title === 'string' && scene.title.includes(',')) problems.push(`${id}'s title has a comma in it, and a <details> summary joins titles with commas, so it would read as two scenes`)
    if (typeof scene.alt === 'string' && /`|\*|\]\(|<|>|(^|\s)_|_(\s|$)/.test(scene.alt)) problems.push(`${id}'s alt has Markdown in it, which an alt shows as written`)
    if (scene.step !== undefined && !/^\d+\. \S/.test(String(scene.step))) problems.push(`${id}: step ${JSON.stringify(scene.step)} is not "<number>. <name>"`)
    if (!appScripts.includes(scene.app)) problems.push(`${id}: apps/${String(scene.app)}/scripts/pictures.mjs does not exist, so nothing takes or checks this picture`)
  }
  if (scenes.filter((scene) => scene.placement === 'hero').length !== 1) problems.push('scenes.json must have exactly one hero scene')
  return problems
}

/**
 * The guard on the guard: every app with a pictures script has a scene, and
 * every region drew a picture. `drawn` is the render, given only by a test
 * that shows a region without one refused.
 */
export function guardProblems({ scenes, record, appScripts }, drawn) {
  const problems = appScripts.filter((app) => !scenes.some((scene) => scene.app === app)).map((app) => `apps/${app}/scripts/pictures.mjs takes no scene of scenes.json, so its check would compare nothing`)
  let rendered = drawn
  try {
    rendered ??= render(scenes, record)
  } catch (error) {
    return [...problems, `the regions could not be rendered, so none drew a picture: ${error.message}`]
  }
  for (const [name, text] of Object.entries(rendered)) if (!text.includes('<img ')) problems.push(`the pictures region "${name}" renders no picture`)
  return problems
}

// `node scripts/pictures/readme.mjs --write` rewrites README.md's pictures regions.
if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const next = rewrite(readFileSync(README, 'utf8'), readScenes(), readRecord())
  if (process.argv.includes('--write')) {
    writeFileSync(README, next, 'utf8')
    console.log(`README.md: ${String(regionNames(readScenes()).length)} pictures regions written from scenes.json and captured.json`)
  } else {
    process.stdout.write(next)
  }
}
