// `codecov.yml`, generated from the workspace.
//
// The component list in that file is one row per package that produces
// coverage, and a package added without a row is simply absent from the report
// -- which is the silent kind of wrong. So the list is derived: `node
// scripts/codecov-config.mjs --write` rewrites the file, and
// `scripts/codecov-config.test.mjs` fails when the committed file is not what
// this produces, naming that command.
//
// **The reasoning that belongs in `codecov.yml` is written here**, because a
// comment in a generated file survives exactly until the next run. The YAML
// comments carry no markdown and no backticks for the same reason: nothing
// renders them, and the generator would have to escape every one.
//
// Built from a list of lines rather than one template literal, which is not
// style. A template literal holding YAML that quotes shell commands needs a
// backslash before every backtick, and getting one wrong is a syntax error in
// a generator whose output nothing would otherwise check.
//
// The policy and most of the words are formancy.ai's, measured there against a
// real report: a pull request comment reading "Patch coverage is 87.87879% ...
// Please review", with a red cross, for a metric that repository does not gate
// on. The precision, informational and component settings below are each an
// answer to one part of that sentence, and this repository inherits the answer.

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/**
 * Every workspace package with a `test:coverage` script, in path order.
 *
 * The script is the right thing to key on rather than the directory listing: a
 * package with no suite would get a component that reports nothing forever and
 * looks like a package nobody tests.
 */
export function coveredPackages(repoRoot = root) {
  const found = []
  for (const group of ['packages', 'apps']) {
    if (!existsSync(join(repoRoot, group))) continue
    for (const name of readdirSync(join(repoRoot, group)).sort()) {
      let manifest
      try {
        manifest = JSON.parse(readFileSync(join(repoRoot, group, name, 'package.json'), 'utf8'))
      } catch {
        continue
      }
      if (manifest.scripts?.['test:coverage'] === undefined) continue
      // An app and a package could share a name, and two components with one id
      // is a report that silently merges them.
      found.push({ path: `${group}/${name}`, id: group === 'apps' ? `app-${name}` : name })
    }
  }
  return found
}

const HEADER = [
  '# Codecov. GENERATED by scripts/codecov-config.mjs -- do not edit.',
  '#',
  '# Run "node scripts/codecov-config.mjs --write" after adding a package.',
  '# scripts/codecov-config.test.mjs fails until the committed file matches what',
  '# that produces, and names the command. The reasoning lives in the generator,',
  '# because a comment written here survives exactly until the next run.',
  '#',
  '# COVERAGE IS REPORTED HERE, NEVER GATED, and this file is what holds that',
  '# against Codecov, whose defaults do the opposite: with no configuration it',
  '# posts project and patch statuses against an "auto" target, so a pull request',
  '# that lowers the number carries a failing check. That is a threshold, and',
  '# vitest.coverage.ts deliberately has none -- a percentage is a number',
  '# somebody can raise without raising confidence, and the exclusions in that',
  '# file exist so the figure means something rather than so it looks good.',
  '# Every status below is informational: it reports the movement and blocks',
  '# nothing.',
]

const BODY = [
  'codecov:',
  '  # The report describes a commit CI has finished with. Without this a comment',
  '  # can arrive mid-run against a partial upload and then correct itself, which',
  '  # reads as the number moving when it is the report arriving.',
  '  require_ci_to_pass: true',
  '  notify:',
  '    wait_for_ci: true',
  '',
  'coverage:',
  '  # One decimal, rounded down. A figure to five decimal places claims a',
  '  # precision the measurement does not have and is harder to compare by eye.',
  '  precision: 1',
  '  round: down',
  '  range: "60...95"',
  '  status:',
  '    project:',
  '      default:',
  '        informational: true',
  '    patch:',
  '      default:',
  '        informational: true',
  '',
  '# One component per package that produces coverage, so the report says WHICH',
  '# of them moved. Without this it is one number for the whole workspace, and an',
  '# adapter losing coverage looks exactly like the core gaining it.',
  'component_management:',
  '  default_rules:',
  '    statuses:',
  '      - type: project',
  '        informational: true',
  '  individual_components:',
]

const FOOTER = [
  '',
  'comment:',
  '  # Components first, because "which package" is the question a reader has, and',
  '  # the per-file table after it because that is the detail.',
  '  layout: "condensed_header, components, condensed_files"',
  '  behavior: default',
  '  # Comment even when nothing moved: a report that appears only on a drop is a',
  '  # report whose absence has two meanings.',
  '  require_changes: false',
  '',
  '# Nothing is ignored here, deliberately. What is left out of the measurement --',
  '# barrels, composition roots, declaration files -- is left out in',
  '# vitest.coverage.ts, where the argument for each exclusion is written down, so',
  '# it never reaches the uploaded report at all. A second list here would be one',
  '# decision in two places.',
]

/** The file, as it should be on disk. */
export function codecovConfig(packages = coveredPackages()) {
  const components = packages.flatMap(({ path, id }) => [
    `    - component_id: ${id}`,
    `      name: ${path}`,
    '      paths:',
    `        - ${path}/**`,
  ])

  return `${[...HEADER, '', ...BODY, ...components, ...FOOTER].join('\n')}\n`
}

// `node scripts/codecov-config.mjs --write`
if (process.argv[1]?.endsWith('codecov-config.mjs')) {
  const text = codecovConfig()
  if (process.argv.includes('--write')) {
    writeFileSync(join(root, 'codecov.yml'), text, 'utf8')
    console.log(`codecov.yml: ${String(coveredPackages().length)} components`)
  } else {
    process.stdout.write(text)
  }
}
