import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, test } from 'vitest'
import { block, blocks, readBlock, replaceBlock } from './generated-block.mjs'

/**
 * The one grammar of a generated region (0035), and every region the
 * repository's Markdown holds held to it.
 */
const repo = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Every tracked Markdown file, as git lists it. */
function trackedMarkdown() {
  return execFileSync('git', ['ls-files', '*.md'], { cwd: repo, encoding: 'utf8' })
    .split('\n')
    .filter((file) => file !== '')
}

describe('a generated block', () => {
  // What is written must be what is read back, with and without a source and
  // a name: a block its own reader could not find would be rewritten into a
  // second copy on the next run.
  test('reads back what it was written with, with or without a source and a name', () => {
    const plain = `# Title\n\n${block('scripts/a.mjs', '| a |\n| - |')}\n\nAfter.\n`
    expect(readBlock(plain, 'scripts/a.mjs')).toBe('| a |\n| - |')
    const named = `${block('scripts/b.mjs', 'one', { from: 'data/b.json', name: 'first' })}\n${block('scripts/b.mjs', 'two', { from: 'data/b.json', name: 'second' })}\n`
    expect(blocks(named).map(({ generator, from, name, body }) => ({ generator, from, name, body }))).toEqual([
      { generator: 'scripts/b.mjs', from: 'data/b.json', name: 'first', body: 'one' },
      { generator: 'scripts/b.mjs', from: 'data/b.json', name: 'second', body: 'two' },
    ])
    const replaced = replaceBlock(named, 'scripts/b.mjs', 'TWO', { name: 'second' })
    expect(readBlock(replaced, 'scripts/b.mjs', { name: 'second' })).toBe('TWO')
    expect(readBlock(replaced, 'scripts/b.mjs', { name: 'first' })).toBe('one')
    expect(replaceBlock(plain, 'scripts/a.mjs', '| a |\n| - |')).toBe(plain)
  })

  // An unclosed block would swallow the rest of the document into the next
  // rewrite; one missing, or there twice, has no single place to be written.
  test('refuses a block that is unclosed, absent or there twice', () => {
    const open = '<!-- generated by scripts/a.mjs; do not edit -->\nbody\n'
    expect(() => blocks(open)).toThrow(/never closed/)
    expect(() => readBlock('# nothing', 'scripts/a.mjs')).toThrow(/exactly once/)
    const twice = `${block('scripts/a.mjs', 'x')}\n${block('scripts/a.mjs', 'y')}`
    expect(() => readBlock(twice, 'scripts/a.mjs')).toThrow(/found 2/)
    expect(() => blocks('<!-- generated by somebody, do not edit -->')).toThrow(/is not "<!-- generated by <generator>/)
  })
})

describe('every generated block in tracked Markdown', () => {
  // A block whose generator was renamed or deleted is a region nobody
  // regenerates, kept in the shape of one that is; a source that is gone is
  // a rendering of nothing.
  test('parses, is closed, and names a generator and a source that exist', () => {
    const found = trackedMarkdown().flatMap((file) => blocks(readFileSync(join(repo, file), 'utf8')).map((entry) => ({ file, ...entry })))
    // The guide's two tables (0032), the README's table and the two adapter lines (0035).
    expect(found.length).toBeGreaterThanOrEqual(5)
    const missing = found.flatMap(({ file, line, generator, from }) => [
      ...(existsSync(join(repo, generator)) ? [] : [`${file}:${String(line)} names the generator ${generator}, which does not exist`]),
      ...(from === undefined || existsSync(join(repo, from)) ? [] : [`${file}:${String(line)} names the source ${from}, which does not exist`]),
    ])
    expect(missing).toEqual([])
  })
})
