// One grammar for every generated region of tracked Markdown (0035):
//
//   <!-- generated by <generator>[ from <source>][: <name>]; do not edit -->
//   <body>
//   <!-- end generated -->
//
// `generator` is the repository-relative script that writes the body, so a
// reader who wants it changed knows what to run; `from`, when the body is a
// rendering of a data file, names that file; `name` tells two blocks of one
// generator in one document apart. The README's tested-on table, the
// adapters' tested-on lines and the getting-started guide's tables (0032) are
// all in it, and scripts/generated-block.test.mjs fails on a block anywhere
// in tracked Markdown that does not parse, is not closed, or names a
// generator or a source that does not exist -- an orphan nobody regenerates.
//
// Node's built-ins only: the getting-started gate runs from a checkout with
// nothing installed, and renders its guide's blocks through this.

const OPEN = /<!-- generated by (\S+?)(?: from (\S+?))?(?:: ([^;]+?))?; do not edit -->/g
const END = '<!-- end generated -->'

/** The opening marker for a block of `generator`. */
export function marker(generator, { from, name } = {}) {
  return `<!-- generated by ${generator}${from === undefined ? '' : ` from ${from}`}${name === undefined ? '' : `: ${name}`}; do not edit -->`
}

/** A whole block: its markers around `body`, with a blank line each side so Markdown reads a table as a table. */
export function block(generator, body, options = {}) {
  return `${marker(generator, options)}\n\n${body.trim()}\n\n${END}`
}

const lf = (text) => text.replaceAll('\r\n', '\n')

/**
 * Every block in `text`, in order: `{ generator, from, name, body, line }`.
 * Throws on an opening marker that is not closed before the next one opens,
 * and on a `<!-- generated by` that is not the grammar at all -- a block in
 * a shape nothing reads is one nothing regenerates.
 */
export function blocks(text) {
  const source = lf(text)
  const found = []
  const opened = [...source.matchAll(OPEN)]
  const mentions = [...source.matchAll(/<!-- generated by /g)].length
  if (mentions !== opened.length) {
    const bad = source.split('\n').findIndex((line) => line.includes('<!-- generated by ') && [...line.matchAll(OPEN)].length === 0)
    throw new Error(`line ${String(bad + 1)}: "<!-- generated by" that is not "<!-- generated by <generator>[ from <source>][: <name>]; do not edit -->"`)
  }
  for (const [index, match] of opened.entries()) {
    const start = match.index + match[0].length
    const end = source.indexOf(END, start)
    const next = opened[index + 1]?.index ?? Number.POSITIVE_INFINITY
    const line = source.slice(0, match.index).split('\n').length
    if (end === -1 || end > next) throw new Error(`line ${String(line)}: the block ${match[0]} is never closed by ${END}`)
    found.push({ generator: match[1], from: match[2], name: match[3], body: source.slice(start, end).trim(), line })
  }
  return found
}

/** The blocks of `generator` named `name` (or unnamed), checked to be exactly one. */
function only(text, generator, { name } = {}) {
  const matching = blocks(text).filter((entry) => entry.generator === generator && entry.name === name)
  if (matching.length !== 1) {
    const what = name === undefined ? `the block ${generator} generates` : `the generated block "${name}"`
    throw new Error(`must hold ${what} exactly once, opened by ${marker(generator, { name })} (with its source, if it has one); found ${String(matching.length)}`)
  }
  return matching[0]
}

/** The body of the one block of `generator` (named `name`, if given). Throws when it is absent, repeated or unclosed. */
export function readBlock(text, generator, options = {}) {
  return only(text, generator, options).body
}

/**
 * `text` with the body of the one block of `generator` (named `name`, if
 * given) replaced by `body`, its marker rewritten to name `from`. Throws when
 * the block is absent, repeated or unclosed, as `readBlock` does.
 */
export function replaceBlock(text, generator, body, options = {}) {
  const source = lf(text)
  const found = only(source, generator, options)
  const opening = [...source.matchAll(OPEN)].find((match) => match[1] === generator && match[3] === found.name)
  const start = opening.index
  const end = source.indexOf(END, start + opening[0].length) + END.length
  return `${source.slice(0, start)}${block(generator, body, { from: options.from ?? found.from, name: found.name })}${source.slice(end)}`
}
