import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, test } from 'vitest'
import { EMPTY_PRESENTATION as CORE_EMPTY_PRESENTATION } from '../../packages/data-core/src/presentation/types.ts'
import { fillFromOperations } from '../../apps/studio/src/policy-model.ts'
import { EMPTY_PRESENTATION, fieldsFromOperations } from './journey.mjs'
import { extractSteps, generatedRegions, GUIDE, inlineCommands, plan, readJourney, render } from './steps.mjs'
import { guideNames, HOST, STUDIO, STUDIO_STEPS } from './walk.mjs'

/**
 * docs/getting-started.md against what the gate runs and sends (0032),
 * without Docker: `pnpm test:repo` holds these on every pull request, and the
 * gate itself (scripts/getting-started.mjs) holds the rest in its own job.
 */
const guide = readFileSync(GUIDE, 'utf8')
const repo = join(GUIDE, '..', '..')

/** The guide from the heading that starts with `from` up to the next one at its level that starts with `to`. */
function section(markdown, from, to) {
  const text = markdown.replaceAll('\r\n', '\n')
  const start = text.indexOf(`\n## ${from}`)
  const end = text.indexOf(`\n## ${to}`, start + 1)
  if (start === -1 || end === -1) throw new Error(`the guide has no section from "## ${from}" to "## ${to}"`)
  return text.slice(start, end)
}

/** What `markdown` sets in bold, and in italics, as a reader sees it: a line break inside is a space. */
function emphasised(markdown) {
  const bold = [...markdown.matchAll(/\*\*([^*]+)\*\*/g)].map((match) => match[1])
  const rest = markdown.replace(/\*\*[^*]+\*\*/g, '')
  const italic = [...rest.matchAll(/(?<![*\w])\*([^*\s][^*]*?)\*(?![*\w])/g)].map((match) => match[1])
  return [...bold, ...italic].map((name) => name.replace(/\s+/g, ' '))
}

describe("the guide's generated values", () => {
  // The values an operator types into the studio and the host page are the
  // ones the gate's journey sends. An edit to journey.json that was not
  // rendered would leave the gate proving one form and the guide describing
  // another, and nothing else would notice.
  test('are what journey.json renders -- run "node scripts/getting-started/steps.mjs --write" otherwise', () => {
    const rendered = render(readJourney())
    expect(generatedRegions(guide)).toEqual(rendered)
  })

  // A region deleted from the guide, or its marker misspelt, would leave
  // nothing to compare, and the comparison above would be of nothing.
  test('are both in the guide, once each', () => {
    expect(() => generatedRegions(guide.replace(/<!-- generated by[^>]*: host; do not edit -->/, ''))).toThrow(/"host" exactly once/)
    expect(Object.keys(generatedRegions(guide))).toEqual(['studio', 'host'])
  })
})

describe("the guide's steps", () => {
  // The committed guide as the gate reads it: one start, the tokens, and the
  // stops last, with only the clone and cd skipped. A guide edited so the gate
  // ran nothing, or skipped a step it should run, fails here rather than as a
  // gate that passes for running less.
  test('are run in order, with only the clone and cd skipped', () => {
    const { run, skipped } = extractSteps(guide)
    expect(skipped.map((block) => block.commands.map((command) => command.split(' ')[0]))).toEqual([['git', 'cd']])
    const { start, before, keep, last } = plan(run)
    expect(start.command).toMatch(/^docker compose --profile stack up /)
    expect(before.filter((step) => step.command.includes(' run --rm token '))).toHaveLength(3)
    expect(keep.map((step) => step.command)).toEqual(['docker compose --profile stack down'])
    expect(last.command).toMatch(/ down -v$/)
  })

  // Each command runs through sh on CI, and an operator types it into sh,
  // PowerShell or cmd. The three agree on letters, digits, spaces and
  // - _ . / : = and on little else: quotes, $, `, |, &, ;, <, >, %, ^,
  // parentheses, braces, globs, ~, #, !, a comma, @ and a trailing backslash
  // each mean something else in at least one of them. A command holding one
  // would pass the gate under sh and could do something else in PowerShell,
  // where no gate runs it.
  test.each([
    ['single quotes', "docker compose exec -T server sh -c 'ls /run'"],
    ['double quotes', 'docker compose run --rm token --subject "ada"'],
    ['a command substitution', 'docker compose run --rm token --subject $(whoami)'],
    ['a variable', 'docker compose run --rm token --subject $USER'],
    ['a backtick', 'docker compose run --rm token --subject `whoami`'],
    ['a pipe', 'docker compose logs server | more'],
    ['an ampersand', 'docker compose up -d && docker compose ps'],
    ['a semicolon', 'docker compose ps; docker compose logs'],
    ['a redirection', 'docker compose logs server > server.log'],
    ['an input redirection', 'docker compose exec -T server sh < script.sh'],
    ['a percent sign', 'docker compose run --rm token --subject %USERNAME%'],
    ['a caret', 'docker compose ps ^'],
    ['parentheses', 'docker compose ps (server)'],
    ['braces', 'docker compose ps {server}'],
    ['a glob', 'docker compose logs seed-*'],
    ['a tilde', 'docker compose --project-directory ~/x ps'],
    ['a hash', 'docker compose ps #server'],
    ['an exclamation mark', 'docker compose ps !'],
    ['a comma', 'docker compose run --rm token --role clerk,auditor'],
    ['an at sign', 'docker compose ps @args'],
    ['a trailing backslash', 'docker compose ps \\'],
  ])('refuse a command with %s, which the shells read differently', (_, command) => {
    expect(() => extractSteps(`\`\`\`sh\n${command}\n\`\`\`\n`)).toThrow(/the same in sh, PowerShell and cmd/)
  })

  // Each refusal is a way a guide could hold a command the gate does not run
  // while the gate stays green.
  test.each([
    ['no block at all', 'Nothing to run.\n', /no ```sh block/],
    ['a skipped block that does more than clone and cd', '<!-- not run by the gate: CI has it -->\n```sh\ngit clone x\ndocker compose up\n```\n', /only git clone and cd may be skipped/],
    ['a clone without the marker', '```sh\ngit clone https://example.invalid/x.git\n```\n', /mark its block/],
    ['a marker before something else', '<!-- not run by the gate: CI has it -->\n\n```sh\ncd x\n```\n', /marker is not on the line before/],
    ['a bash block', '```bash\ndocker compose up -d\n```\n', /```bash block is neither run/],
    ['a block with no language', '```\ndocker compose up -d\n```\n', /``` block is neither run/],
    ['an indented block in a list', '1. Start it:\n\n   ```bash\n   docker compose up -d\n   ```\n', /```bash block is neither run/],
    ['two commands in one block', '```sh\ndocker compose up -d\ndocker compose ps\n```\n', /holds 2 commands/],
    ['a command other than compose', '```sh\ncurl http://127.0.0.1:4394/health\n```\n', /not a docker compose command/],
    ['a block never closed', '```sh\ndocker compose up -d\n', /never closed/],
  ])('refuse %s', (_, markdown, sentence) => {
    expect(() => extractSteps(markdown)).toThrow(sentence)
  })

  // An indented fence is still a fence: a ```sh block inside a list item is
  // run, not missed.
  test('find a ```sh block inside a list item', () => {
    const { run } = extractSteps('1. Start it:\n\n   ```sh\n   docker compose ps\n   ```\n')
    expect(run).toEqual([{ line: 4, command: 'docker compose ps' }])
  })

  // The gate starts the stack, mints, starts it again, checks, and stops. A
  // guide that started twice, stopped in the middle or left its volumes
  // behind would be run in an order it does not describe.
  test.each([
    ['no start', ['docker compose run --rm token', 'docker compose down -v'], /0 steps that start/],
    ['two starts', ['docker compose up -d', 'docker compose up -d', 'docker compose down -v'], /2 steps that start/],
    ['no stop', ['docker compose up -d'], /never stops/],
    ['a stop before the start', ['docker compose down', 'docker compose up -d', 'docker compose down -v'], /before it starts it/],
    ['a step after a stop', ['docker compose up -d', 'docker compose down', 'docker compose ps', 'docker compose down -v'], /before its last step/],
    ['a last stop that keeps the volumes', ['docker compose up -d', 'docker compose down'], /does not delete/],
    // The guide promises that `down` keeps the data, the secrets and the
    // forms. The gate holds that by starting again after it; a guide with no
    // such stop would leave the gate nothing to start again after, and the
    // promise would go unchecked without anybody noticing.
    ['no stop that keeps the volumes', ['docker compose up -d', 'docker compose down -v'], /never stops the stack keeping its volumes/],
  ])('are refused with %s', (_, commands, sentence) => {
    expect(() => plan(commands.map((command, index) => ({ line: index + 1, command })))).toThrow(sentence)
  })
})

describe("the guide's commands in running text", () => {
  // Section 7 names commands inline, for an operator whose stack is not
  // well. The gate runs each one against the running stack, so one that
  // broke would fail it; these say which the gate finds, and which it refuses
  // to run there.
  test('are found in the guide, apart from the ones its blocks run', () => {
    const { run } = extractSteps(guide)
    const found = inlineCommands(guide, run)
    expect(found.length).toBeGreaterThan(0)
    expect(found.filter((entry) => !entry.command.startsWith('docker compose '))).toEqual([])
    // The one stop section 7 names inline is the block section 6 runs.
    expect(found.filter((entry) => / down(\s|$)/.test(entry.command))).toEqual([])
  })

  // Markdown joins a code span broken over two lines with a space; a reader
  // that did not would miss the command, or run half of it.
  test('are read across a line break, and not from code blocks', () => {
    const markdown = 'Run `docker compose\n--profile stack ps -a` now.\n\n```text\n`docker compose logs`\n```\n'
    expect(inlineCommands(markdown, [])).toEqual([{ line: 1, command: 'docker compose --profile stack ps -a' }])
  })

  // Run against the running stack, a start or a stop would change what the
  // gate is checking under it; one that is a block's command is run as that
  // step already. And a command in running text is typed into some shell too.
  test.each([
    ['a start that is no block', 'Run `docker compose up -d` again.\n', /starts or stops the stack/],
    ['a stop that is no block', 'Clean up with `docker compose --profile stack down -v --remove-orphans`.\n', /starts or stops the stack/],
    ['a command the shells read differently', "Run `docker compose exec server sh -c 'ls'`.\n", /the same in sh, PowerShell and cmd/],
  ])('refuse %s', (_, markdown, sentence) => {
    expect(() => inlineCommands(markdown, [])).toThrow(sentence)
  })
})

describe("the guide's names for the studio's and the host page's controls", () => {
  // The guide tells an operator which control to use by the name the app
  // gives it. Those names come from walk.mjs, which the studio's and the host
  // page's guide tests drive the apps by. A name in the prose that is not
  // there is one nothing holds: an app could rename the control, its own
  // tests with it, and the guide would go on naming what is not on screen.
  test('in bold or italics in sections 4 and 5 are all ones the apps are driven by', () => {
    const known = guideNames(readJourney())
    expect(emphasised(section(guide, '4.', '6.')).filter((name) => !known.has(name))).toEqual([])
  })

  // The other way round: a name walk.mjs keeps for the guide's prose that the
  // guide no longer says is held for nothing, and its test proves nothing.
  test('kept for the prose are all in it', () => {
    const said = new Set(emphasised(section(guide, '4.', '6.')))
    expect([...Object.values(STUDIO), ...Object.values(STUDIO_STEPS), ...Object.values(HOST)].filter((name) => !said.has(name))).toEqual([])
  })

  // Not vacuous: the extraction finds bold and italic names, and only those.
  test('are read from bold and italics', () => {
    expect(emphasised('Press **Sign\nin**; it says *Saved.* and 2 * 3 * 4 is not a name.')).toEqual(['Sign in', 'Saved.'])
  })
})

describe("the guide's Compose", () => {
  /** The releases a workflow's getting-started job pins in its matrix, beside the runner's own. */
  function pinned(file) {
    const text = readFileSync(join(repo, '.github', 'workflows', file), 'utf8').replaceAll('\r\n', '\n')
    const start = text.indexOf('\n  getting-started:\n')
    if (start === -1) return []
    const next = text.slice(start + 1).search(/\n {2}[a-z][\w-]*:\n/)
    const job = next === -1 ? text.slice(start) : text.slice(start, start + 1 + next)
    return [...job.matchAll(/^\s+- compose: (\d+\.\d+\.\d+)$/gm)].map((match) => match[1])
  }

  // Section 0 says which Compose the guide works with. The getting-started
  // job runs the gate with the oldest release it names, so a compose.yaml
  // that needs a newer one fails there; this fails when the sentence and the
  // pin disagree, so neither moves without the other.
  test('is the oldest release CI and the release run the guide with', () => {
    const [ci, release] = [pinned('ci.yml'), pinned('release.yml')]
    expect(ci).toHaveLength(1)
    expect(release).toEqual(ci)
    const [major, minor] = ci[0].split('.')
    expect(section(guide, '0.', '1.')).toContain(`Compose ${major}.${minor} or later`)
  })
})

describe("the guide's addresses", () => {
  // compose.yaml publishes the web front on FORMANCY_DATA_WEB_PORT, its
  // default otherwise. Section 0 tells an operator whose port is taken to set
  // it; a link that then names the default reaches nothing. So every
  // paragraph with an address names the setting, and the address's port is
  // compose's default, read from compose.yaml rather than typed here.
  test('use the port compose publishes the web front on, and name the setting that changes it', () => {
    const port = /\$\{FORMANCY_DATA_WEB_PORT:-(\d+)\}:8080/.exec(readFileSync(join(repo, 'compose.yaml'), 'utf8'))?.[1]
    expect(port).toMatch(/^\d+$/)
    const addressed = guide
      .replaceAll('\r\n', '\n')
      .split(/\n\s*\n/)
      .filter((paragraph) => /https?:\/\/(127\.0\.0\.1|localhost)[:/]/.test(paragraph))
    expect(addressed.length).toBeGreaterThan(0)
    const ports = addressed.flatMap((paragraph) => [...paragraph.matchAll(/https?:\/\/(?:127\.0\.0\.1|localhost):(\d+)/g)].map((match) => match[1]))
    expect(new Set(ports)).toEqual(new Set([port]))
    expect(addressed.filter((paragraph) => !paragraph.includes('FORMANCY_DATA_WEB_PORT')).map((paragraph) => paragraph.slice(0, 60))).toEqual([])
  })
})

describe("the gate's copies", () => {
  // The gate runs from a checkout with nothing installed, so it cannot import
  // data-core. A presentation that changed shape in data-core and not here
  // would publish a bundle the server refuses -- found in the gate's own job,
  // twenty minutes in, rather than here.
  test('of EMPTY_PRESENTATION is data-core\'s', () => {
    expect(EMPTY_PRESENTATION).toEqual(CORE_EMPTY_PRESENTATION)
  })

  // The guide says "press Fill every field from the operations", and the gate
  // publishes what its copy of that button gives. If the studio's rule
  // changed, the gate would go on proving a policy the operator no longer gets.
  test("of the studio's Fill every field from the operations agrees with it", () => {
    const writes = (create, update) => ({ create, update })
    const bindings = {
      fields: [
        { field: 'id', kind: 'column', column: 'id', writes: writes(false, false) },
        { field: 'status', kind: 'column', column: 'status', writes: writes(true, true) },
        { field: 'amount', kind: 'column', column: 'amount', writes: writes(true, false) },
        { field: 'reviewed', kind: 'column', column: 'reviewed', writes: writes(false, true) },
        { field: 'tenant', kind: 'column', column: 'tenant_id', writes: writes(true, true) },
        { field: 'customer', kind: 'lookup', columns: ['tenant_id', 'customer_no'], writes: writes(true, false) },
      ],
    }
    const policy = {
      version: 1,
      operations: { read: ['clerk', 'auditor'], create: ['clerk'], update: ['clerk', 'manager'] },
      fields: {},
      rowFilters: [{ column: 'tenant_id', attribute: 'tenant' }],
      lookups: {},
    }
    expect(fieldsFromOperations(policy, bindings)).toEqual(fillFromOperations(policy, bindings).fields)
    // Not vacuous: the case holds a field written by nobody, one pinned, and one written by both operations' roles.
    expect(fieldsFromOperations(policy, bindings)).toMatchObject({
      id: { write: [] },
      tenant: { write: [] },
      status: { read: ['clerk', 'auditor'], write: ['clerk', 'manager'] },
    })
  })
})
